from dataclasses import dataclass

@dataclass
class Key:
    NotificationEmail: str = "captcha_failed_email"
    WindowsPlanName: str = "plan_name"
    Operation: str = "operation"
    TriggerType: str = "trigger_type"
    Hour: str = "hour"
    Minute: str = "minute"
    ShortName: str = "short_name"
    ExecuteTime: str = "execute_time"
    ExecuteDay: str = "execute_day"
    TaskID: str = "plan_id"
    Multiple: str = "Multiple"
    Calendar: str = "calendar"
    MultipleName: str = "multiple_name"
    DefaultWindowsPlanName: str = "AutoClock_Windows_Plan"
    Year: str = "year"
    Month: str = "month"
    Day: str = "day"
    Once: str = "Once"
    Daily: str = "Daily"
    Weekly: str = "Weekly"
    Monthly: str = "Monthly"
    SendEmailWhenSuccess: str = "send_email_success"
    SendEmailWhenFailed: str = "send_email_failed"
    UserName: str = "user_name"
    UserPassword: str = "user_password"
    CaptchaRetryTimes: str = "captcha_retry_times"
    CaptchaToleranceAngle: str = "captcha_tolerance_angle"
    DriverPath: str = "driver_path"
    AlwaysRetry: str = "always_retry_check_box"
    ShutDownWindows: str = "Shut Down Windows"
    WindowsSleep: str = "Windows Sleep"
    AutoClock: str = "Auto Clock"
    Unknown: str = "Unknown"
    Empty: str = ""
